### ISSUE TITLE
config errors results in weird missing class error

### ISSUE THREAD

**Issue by kruisdraad** [AbuseIO/AbuseIO#214]
if you brake the configuration file (any of them) resulting in a PHP errors (missing ; or , etc ... anything that results in php errors) does not break the laravel framework. Instead it would report something like 

PHP Fatal error:  Uncaught ReflectionException: Class log does not exist in /opt/abuseio/bootstrap/cache/compiled.php:1291
Stack trace:
#0 /opt/abuseio/bootstrap/cache/compiled.php(1291): ReflectionClass->__construct('log')
#1 /opt/abuseio/bootstrap/cache/compiled.php(1242): Illuminate\Container\Container->build('log', Array)
#2 /opt/abuseio/bootstrap/cache/compiled.php(1783): Illuminate\Container\Container->make('log', Array)
#3 /opt/abuseio/bootstrap/cache/compiled.php(1334): Illuminate\Foundation\Application->make('log')
#4 /opt/abuseio/bootstrap/cache/compiled.php(1318): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 /opt/abuseio/bootstrap/cache/compiled.php(1304): Illuminate\Container\Container->getDependencies(Array, Array)
#6 /opt/abuseio/bootstrap/cache/compiled.php(1242): Illuminate\Container\Container->build('AbuseIO\\Excepti...', Array)
#7 /opt/abuseio/bootstrap/cache/compiled.php(1783): Illuminate\Container\Container->make('AbuseIO\\Excepti...', Array)
#8 /opt/abuseio/bootstrap/cache/c in /opt/abuseio/bootstrap/cache/compiled.php on line 1291
Script php artisan clear-compiled handling the post-update-cmd event returned with error code 255

In all broken combinations i've seen the error that the class log could not be found. Perhaps we could build something that would detect that ... or ask laravel to fix that.

**Comment by kruisdraad** [comment]
fixed in 5.0, laravel 12.x addresses this.
