### ISSUE TITLE
incoming email that contains strange chars confuses the handler

### ISSUE THREAD

**Issue by kruisdraad** [AbuseIO/AbuseIO#217]
Jan 26 13:15:05 abuseio abuseio[6396]: production.INFO: AbuseIO\Jobs\EmailProcess: Queued worker is starting the processing of email file: mailarchive/20170126/63296870-4eb4-431f-8df4-7727dc3edc08.eml
Jan 26 13:15:05 abuseio abuseio[6396]: production.ERROR: ErrorException: iconv(): Detected an illegal character in input string in /opt/abuseio/vendor/php-mime-mail-parser/php-mime-mail-parser/src/Charset.php:326 Stack trace: #0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'iconv(): Detect...', '/opt/abuseio/ve...', 326, Array) #1 /opt/abuseio/vendor/php-mime-mail-parser/php-mime-mail-parser/src/Charset.php(326): iconv('', 'UTF-8//TRANSLIT', '[ SpamCop V4.8....') #2 /opt/abuseio/vendor/php-mime-mail-parser/php-mime-mail-parser/src/Parser.php(229): PhpMimeMailParser\Charset->decodeCharset('[ SpamCop V4.8....', NULL) #3 /opt/abuseio/app/Jobs/EmailProcess.php(93): PhpMimeMailParser\Parser->getMessageBody() #4 [internal function]: AbuseIO\Jobs\EmailProcess->handle() #5 /opt/abuseio/bootstrap/cache/compiled.php(1187): call_user_func_array(Array, Array) #6 /opt/abuseio/bootstrap/cache/compiled.php(9499): Illuminate\Container\Container->call(Array) #7 [internal function]: Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(AbuseIO\Jobs\EmailProcess)) #8 /opt/abuseio/bootstrap/cache/compiled.php(9651): call_user_func(Object(Closure), Object(AbuseIO\Jobs\EmailProcess)) #9 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(AbuseIO\Jobs\EmailProcess)) #10 /opt/abuseio/bootstrap/cache/compiled.php(9633): call_user_func(Object(Closure), Object(AbuseIO\Jobs\EmailProcess)) #11 /opt/abuseio/bootstrap/cache/compiled.php(9506): Illuminate\Pipeline\Pipeline->then(Object(Closure)) #12 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(43): Illuminate\Bus\Dispatcher->dispatchNow(Object(AbuseIO\Jobs\EmailProcess), Object(Closure)) #13 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(129): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\DatabaseJob), Array) #14 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Queue/Jobs/DatabaseJob.php(50): Illuminate\Queue\Jobs\Job->resolveAndFire(Array) #15 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(218): Illuminate\Queue\Jobs\DatabaseJob->fire() #16 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(159): Illuminate\Queue\Worker->process('database', Object(Illuminate\Queue\Jobs\DatabaseJob), '1', '0') #17 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(111): Illuminate\Queue\Worker->pop(NULL, 'abuseio_email_i...', '0', '3', '1') #18 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(85): Illuminate\Queue\Worker->runNextJobForDaemon(NULL, 'abuseio_email_i...', '0', '3', '1') #19 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(102): Illuminate\Queue\Worker->daemon(NULL, 'abuseio_email_i...', '0', '256', '3', '1') #20 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(70): Illuminate\Queue\Console\WorkCommand->runWorker(NULL, 'abuseio_email_i...', '0', '256', true) #21 [internal function]: Illuminate\Queue\Console\WorkCommand->fire() #22 /opt/abuseio/bootstrap/cache/compiled.php(1187): call_user_func_array(Array, Array) #23 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Console/Command.php(150): Illuminate\Container\Container->call(Array) #24 /opt/abuseio/vendor/symfony/console/Command/Command.php(254): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #25 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #26 /opt/abuseio/vendor/symfony/console/Application.php(847): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #27 /opt/abuseio/vendor/symfony/console/Application.php(190): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #28 /opt/abuseio/vendor/symfony/console/Application.php(121): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #29 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #30 /opt/abuseio/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #31 {main}
Jan 26 13:15:09 abuseio abuseio[6396]: production.ERROR: ErrorException: call_user_func() expects parameter 1 to be a valid callback, cannot access protected method AbuseIO\Jobs\EmailProcess::failed() in /opt/abuseio/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php:77 Stack trace: #0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'call_user_func(...', '/opt/abuseio/ve...', 77, Array) #1 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(77): call_user_func(Array, Object(AbuseIO\Jobs\EmailProcess)) #2 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(212): Illuminate\Queue\CallQueuedHandler->failed(Array) #3 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(271): Illuminate\Queue\Jobs\Job->failed() #4 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(211): Illuminate\Queue\Worker->logFailedJob('database', Object(Illuminate\Queue\Jobs\DatabaseJob)) #5 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(159): Illuminate\Queue\Worker->process('database', Object(Illuminate\Queue\Jobs\DatabaseJob), '1', '0') #6 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(111): Illuminate\Queue\Worker->pop(NULL, 'abuseio_email_i...', '0', '3', '1') #7 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(85): Illuminate\Queue\Worker->runNextJobForDaemon(NULL, 'abuseio_email_i...', '0', '3', '1') #8 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(102): Illuminate\Queue\Worker->daemon(NULL, 'abuseio_email_i...', '0', '256', '3', '1') #9 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(70): Illuminate\Queue\Console\WorkCommand->runWorker(NULL, 'abuseio_email_i...', '0', '256', true) #10 [internal function]: Illuminate\Queue\Console\WorkCommand->fire() #11 /opt/abuseio/bootstrap/cache/compiled.php(1187): call_user_func_array(Array, Array) #12 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Console/Command.php(150): Illuminate\Container\Container->call(Array) #13 /opt/abuseio/vendor/symfony/console/Command/Command.php(254): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #14 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #15 /opt/abuseio/vendor/symfony/console/Application.php(847): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #16 /opt/abuseio/vendor/symfony/console/Application.php(190): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #17 /opt/abuseio/vendor/symfony/console/Application.php(121): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #18 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #19 /opt/abuseio/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #20 {main}

**Comment by justcfx2u** [comment]
This is happening to me too and is causing failed jobs to accumulate. This error is occurring so early in the process that it is aborting before it is able to send an admin alert notification/forward.

**Comment by marknl** [comment]
Is there sample data to use that fails? "strange chars" is kind of generic.

**Comment by kruisdraad** [comment]
just add some chinese or cirrilec chars in a body and the mime parser goes boom

**Comment by imme-emosol** [comment]
It seems to be something upstream; https://github.com/php-mime-mail-parser/php-mime-mail-parser/pull/137 .
Duct-taping it at AbuseIO's side could perhaps be done by transliteration of $rawEmail .
https://github.com/AbuseIO/AbuseIO/blob/aeeabaa98ea3c659e638b9ae87b816ab18c6de72/app/Jobs/EmailProcess.php#L86

Another option might be to provide a custom implementation of https://github.com/php-mime-mail-parser/php-mime-mail-parser/blob/master/src/Contracts/CharsetManager.php .
Although https://github.com/php-mime-mail-parser/php-mime-mail-parser/issues/179 mentions that there are some issues with using php's multibyte functions on headers and stuff, so perhaps conversion needs to be done on the rawEmail as well.

**Comment by kruisdraad** [comment]
We have upgrade AbuseIO 5.0 to LTS12 with 3.1.9, which seems to have solved this issue. If the issue is still existing in 5.0 provide how to reproduce and reopen this ticket. For now listing as solved by upgrade.
