### ISSUE TITLE
AbuseIO 4.2 - doctrine/dbal dep missing

### ISSUE THREAD

**Issue by pettai** [AbuseIO/AbuseIO#354]
abuseio-docker gets lots of crap in the syslog upon startup:

```
[...]
Jun 11 16:22:17 cf7f34311622 AbuseIO[15]: [2020-06-11 16:22:17] local.ERROR: SQLSTATE[HY000] [2002] Connection refused {"exception":"[object] (Doctrine\\DBAL\\Driver\\PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /opt/abuseio/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31, PDOException(code: 2002): SQLSTATE[HY000] [2002] Connection refused at /opt/abuseio/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)#012[stacktrace]#012#0 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(65): Doctrine\\DBAL\\Driver\\PDOConnection->__construct('mysql:host=127....', 'root', 'abuseio', Array)#012#1 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(44): Illuminate\\Database\\Connectors\\Connector->createPdoConnection('mysql:host=127....', 'root', 'abuseio', Array)#012#2 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(24): Illuminate\\Database\\Connectors\\Connector->createConnection('mysql:host=127....', Array, Array)#012#3 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(182): Illuminate\\Database\\Connectors\\MySqlConnector->connect(Array)#012#4 [internal function]: Illuminate\\Database\\Connectors\\ConnectionFactory->Illuminate\\Database\\Connectors\\{closure}()#012#5 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Database/Connection.php(915): call_user_func(Object(Closure))#012#6 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(108): Illuminate\\Database\\Connection->getPdo()#012#7 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(92): Illuminate\\Database\\Connection->createTransaction()#012#8 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(23): Illuminate\\Database\\Connection->beginTransaction()#012#9 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Queue/DatabaseQueue.php(197): Illuminate\\Database\\Connection->transaction(Object(Closure))#012#10 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(246): Illuminate\\Queue\\DatabaseQueue->pop('abuseio_email_i...')#012#11 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(107): Illuminate\\Queue\\Worker->getNextJob(Object(Illuminate\\Queue\\DatabaseQueue), 'abuseio_email_i...')#012#12 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\\Queue\\Worker->daemon('database', 'abuseio_email_i...', Object(Illuminate\\Queue\\WorkerOptions))#012#13 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(85): Illuminate\\Queue\\Console\\WorkCommand->runWorker('database', 'abuseio_email_i...')#012#14 [internal function]: Illuminate\\Queue\\Console\\WorkCommand->handle()#012#15 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)#012#16 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()#012#17 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))#012#18 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)#012#19 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Console/Command.php(179): Illuminate\\Container\\Container->call(Array)#012#20 /opt/abuseio/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))#012#21 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Console/Command.php(166): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))#012#22 /opt/abuseio/vendor/symfony/console/Application.php(1000): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))#012#23 /opt/abuseio/vendor/symfony/console/Application.php(271): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Queue\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))#012#24 /opt/abuseio/vendor/symfony/console/Application.php(147): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))#012#25 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Console/Application.php(89): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))#012#26 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))#012#27 /opt/abuseio/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))#012#28 {main}#012"}
```

This can be avoided by letting composer also install `doctrine/dbal`.

(While I do understand that postgresql isn't going to be used, it makes it easier to spot the "real" problems if the verbose yet harmless errors are taken out of the equation... )

**Comment by kruisdraad** [comment]
AbuseIO docker is currently broken and needs to be replaced with a version 5.0-dev installation of AbuseIO. This is planned at a different level. At this time Ansible (which also needs to be updated) will be prioritized first.
