### ISSUE TITLE
Class log does not exist

### ISSUE THREAD

**Issue by Rudrochou** [AbuseIO/AbuseIO#399]
When installing AbuseIO from tarball on Ubuntu 22 (PHP 7.0.33-68+ubuntu22.04.1+deb.sury.org+2, Apache 2.4.57) there is a white page with the following PHP error:
```
PHP Fatal error:  Uncaught ReflectionException: Class log does not exist in /opt/abuseio/vendor/laravel/framework/src/Illuminate/Container/Container.php:741
Stack trace:
#0 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Container/Container.php(741): ReflectionClass->__construct('log')
#1 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\\Container\\Container->build('log', Array)
#2 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\\Container\\Container->make('log', Array)
#3 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Container/Container.php(842): Illuminate\\Foundation\\Application->make('log')
#4 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Container/Container.php(805): Illuminate\\Container\\Container->resolveClass(Object(ReflectionParameter))
#5 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Container/Container.php(775): Illuminate\\Container\\Container->getDependencies(Array, Array)
#6 /opt/abuseio/vendor/laravel/ in /opt/abuseio/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 741
```

**Comment by miguel456** [comment]
I hate to be the one asking this question, but is this still maintained? Becase at the moment, it looks like the project is effectively dead... I'm going to fork it and _might_ pick it up

**Comment by kruisdraad** [comment]
The unit test works and we dont have this issue, opening a issue doesn't mean we can provide support on each installation. My guess is you missed an installation step causing this.

AbuseIO is still maintained, but it is a open source project and there is no paid employees that code on this, just volonteers.

**Comment by kruisdraad** [comment]
missed step or incorrect setup
