### ISSUE TITLE
AbuseIO and PHP 8.3 

### ISSUE THREAD

**Issue by devz3r0** [AbuseIO/AbuseIO#404]
Hi,

as PHP 7.x is EOL for already a long time, did anyone of you try to set it up on a recent PHP version?
If yes and if successful, are there some hints and tipps what needs to be adapt, or were there no requirement to use a more recent version of php?
I just tried a manual install with ubuntu 24.04 and php 8.3 and just run into the same issue as #399 as I tried to run the migration command.

regards devzero

**Comment by kruisdraad** [comment]
It would help if you use the same issue ID for the same problems, add logs as well as making sure you followed all the installation steps. Issue 399 was related due to missing steps, likely a composer install that was incomplete. I will have a look with Ubuntu 24.04 LTS when i got time this weekend. PHP8 was tested, but likely with 8.0-8.1 and not 8.3 yet.

**Comment by reulnl** [comment]
I'm receiving the following error when running `php artisan migrate` on Ubuntu 24.04 with PHP 8.3.6:

```
PHP Fatal error:  During inheritance of ArrayAccess: Uncaught ErrorException: Return type of Illuminate\Http\Request::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /opt/abuseio/vendor/laravel/framework/src/Illuminate/Http/Request.php:846
Stack trace:
#0 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Http/Request.php(14): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /opt/abuseio/vendor/composer/ClassLoader.php(444): include('...')
#2 /opt/abuseio/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile()
#3 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/SetRequestForConsole.php(20): Composer\Autoload\ClassLoader->loadClass()
#4 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(203): Illuminate\Foundation\Bootstrap\SetRequestForConsole->bootstrap()
#5 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(208): Illuminate\Foundation\Application->bootstrapWith()
#6 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(105): Illuminate\Foundation\Console\Kernel->bootstrap()
#7 /opt/abuseio/artisan(33): Illuminate\Foundation\Console\Kernel->handle()
#8 {main} in /opt/abuseio/vendor/laravel/framework/src/Illuminate/Http/Request.php on line 14
PHP Fatal error:  Uncaught ErrorException: Method ReflectionParameter::getClass() is deprecated in /opt/abuseio/vendor/laravel/framework/src/Illuminate/Container/Container.php:795
Stack trace:
#0 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Container/Container.php(774): Illuminate\Container\Container->getDependencies()
#2 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build()
#3 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make()
#4 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Container/Container.php(220): Illuminate\Foundation\Application->make()
#5 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Container/Container.php(738): Illuminate\Container\Container->Illuminate\Container\{closure}()
#6 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build()
#7 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make()
#8 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(154): Illuminate\Foundation\Application->make()
#9 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(79): Illuminate\Foundation\Bootstrap\HandleExceptions->getExceptionHandler()
#10 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException()
#11 {main}
  thrown in /opt/abuseio/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 795
```

Would be great if PHP 8.3 could be supported on Ubuntu 24.04.

**Comment by kruisdraad** [comment]
PHP 8.3 is not supported in 4.x and will never be due to LTS contraints. PHP 8.4 is supported with AbuseIO 5.0 (but far from ready)
