### ISSUE TITLE
Password reset yields: InvalidArgumentException in FileViewFinder.php line 137: View [emails.password] not found.

### ISSUE THREAD

**Issue by hkraal** [AbuseIO/AbuseIO#58]
Credits @michelzimmerman:

When trying to request a password link at /password/email by filling in the e-mail address and submitting the form the following error shows.

```
Jan 15 11:08:38 abuse01 abuseio[29401]: production.ERROR: exception 'InvalidArgumentException' with message 'View [emails.password] not found.' in /opt/abuseio/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php:137 Stack trace: #0 /opt/abuseio/vendor/laravel/framework/src/Illuminate/View/FileViewFinder.php(79): Illuminate\View\FileViewFinder->findInPaths('emails.password', Array) #1 /opt/abuseio/vendor/laravel/framework/src/Illuminate/View/Factory.php(151): Illuminate\View\FileViewFinder->find('emails.password') #2 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(464): Illuminate\View\Factory->make('emails.password', Array) #3 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(331): Illuminate\Mail\Mailer->getView('emails.password', Array) #4 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(171): Illuminate\Mail\Mailer->addContent(Object(Illuminate\Mail\Message), 'emails.password', NULL, NULL, Array) #5 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Auth/Passwords/PasswordBroker.php(119): Illuminate\Mail\Mailer->send('emails.password', Array, Object(Closure)) #6 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Auth/Passwords/PasswordBroker.php(93): Illuminate\Auth\Passwords\PasswordBroker->emailResetLink(Object(AbuseIO\Models\User), '965c2ffc9d26fed...', Object(Closure)) #7 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(219): Illuminate\Auth\Passwords\PasswordBroker->sendResetLink(Array, Object(Closure)) #8 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Foundation/Auth/ResetsPasswords.php(37): Illuminate\Support\Facades\Facade::__callStatic('sendResetLink', Array) #9 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Foundation/Auth/ResetsPasswords.php(37): Illuminate\Support\Facades\Password::sendResetLink(Array, Object(Closure)) #10 [internal function]: AbuseIO\Http\Controllers\Auth\PasswordController->postEmail(Object(Illuminate\Http\Request)) #11 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(256): call_user_func_array(Array, Array) #12 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(164): Illuminate\Routing\Controller->callAction('postEmail', Array) #13 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(112): Illuminate\Routing\ControllerDispatcher->call(Object(AbuseIO\Http\Controllers\Auth\PasswordController), Object(Illuminate\Routing\Route), 'postEmail') #14 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #15 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request)) #16 /opt/abuseio/app/Http/Middleware/RedirectIfAuthenticated.php(45): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #17 [internal function]: AbuseIO\Http\Middleware\RedirectIfAuthenticated->handle(Object(Illuminate\Http\Request), Object(Closure)) #18 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array) #19 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #20 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request)) #21 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then(Object(Closure)) #22 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(69): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(AbuseIO\Http\Controllers\Auth\PasswordController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'postEmail') #23 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'AbuseIO\Http\Co...', 'postEmail') #24 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request)) #25 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Routing/Router.php(708): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #26 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request)) #27 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request)) #28 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #29 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request)) #30 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Routing/Router.php(710): Illuminate\Pipeline\Pipeline->then(Object(Closure)) #31 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Routing/Router.php(675): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request)) #32 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request)) #33 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(236): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #34 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request)) #35 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request)) #36 /opt/abuseio/app/Http/Middleware/Locale.php(51): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #37 [internal function]: AbuseIO\Http\Middleware\Locale->handle(Object(Illuminate\Http\Request), Object(Closure)) #38 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array) #39 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #40 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure)) #41 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array) #42 /opt/abuseio/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #43 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure)) #44 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array) #45 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #46 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure)) #47 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array) #48 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request)) #49 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure)) #50 /opt/abuseio/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_arra

```

**Comment by kruisdraad** [comment]
Fixed, please confirm if the problem is resolved

**Comment by hkraal** [comment]
Confirmed fix

**Comment by Noumamayo** [comment]
InvalidArgumentException in C:\wamp64\www\LaravelAPI\vendor\laravel\framework\src\Illuminate\View\FileViewFinder.php line 137:
View [helo word] not found.
